name: Inception

services:
  nginx:
    restart: unless-stopped
    build:
      args:
        UID: ${UID}
        GID: ${GID}
      context: ./nginx/
      dockerfile: Dockerfile
    image: nginx:1.0.0
    ports:
      - "443:443"
    volumes:
      - /home/cdomet-d/data/wp-data:/var/www/html
    secrets:
      - cert.pem
      - key.pem
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    restart: unless-stopped
    build:
      args:
        UID: ${UID}
        GID: ${GID}
      context: ./wordpress/
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    image: wordpress:1.0.0
    env_file:
      - path: ~/env-files/wp.env
      - path: ~/env-files/.env
    volumes:
      - /home/cdomet-d/data/wp-data:/var/www/html
    secrets:
      - db-usr-pw
      - wp-su-mail
      - wp-su-pw
      - wp-usr-pw
      - dump.sql
    networks:
      - inception

  mariadb:
    restart: unless-stopped
    build:
      args:
        UID: ${UID}
        GID: ${GID}
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0.0
    env_file:
      - path: ~/env-files/wp.env
      - path: ~/env-files/.env
    secrets:
      - db-root-pw
      - db-usr-pw
      - dump.sql
    volumes:
      - /home/cdomet-d/data/mdb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/utils/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - inception

networks:
  inception:
    driver: bridge
    name: inception

secrets:
  db-root-pw:
    file: ~/docker-secrets/db-root-pw
  db-usr-pw:
    file: ~/docker-secrets/db-usr-pw
  wp-su-pw:
    file: ~/docker-secrets/wp-su-pw
  wp-usr-pw:
    file: ~/docker-secrets/wp-usr-pw
  wp-su-mail:
    file: ~/docker-secrets/wp-su-mail
  cert.pem:
    file: ~/docker-secrets/cert.pem
  key.pem: 
    file: ~/docker-secrets/key.pem
  dump.sql:
    file: ~/docker-secrets/dump.sql