name: Inception

services:
  nginx:
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    image: inception-nginx
    ports:
      - "8443:443"
    volumes:
      - wordpress-data:/var/www/html

  wordpress:
    build:
      context: ./srcs/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    image: inception-wp
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp-manager
      WORDPRESS_DB_PASSWORD: /run/secrets/user

  mariadb:
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb
    secrets:
      - root
      - user
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root
      MYSQL_PASSWORD_FILE: /run/secrets/user
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-manager
volumes:
  wordpress-data:
  mariadb-data:
secrets:
  root:
    file: ~/docker-secrets/root
  user:
    file: ~/docker-secrets/user