name: Inception

services:
  nginx:
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    image: inception-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp-data:/var/www/html
    secrets:
      - cert.pem
      - key.pem
    depends_on:
      - wp

  wp:
    build:
      context: ./srcs/wordpress/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    image: inception-wp
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp-manager
      WORDPRESS_DB_PASSWORD: /run/secrets/user
      WP_ADMIN_PW: /run/secrets/wpsu
      WP_ADMIN_MAIL: /run/secrets/wpsu-mail
    secrets:
      - db-user
      - wpsu
      - wpsu-mail

  db:
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb
    secrets:
      - db-root
      - db-user
    volumes:
      - mdb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root
      MYSQL_PASSWORD_FILE: /run/secrets/db-user
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-manager
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  wp-data:
  mdb-data:

networks:
  inception:
    driver: bridge
    name: inception

secrets:
  db-root:
    file: ~/docker-secrets/dbroot
  db-user:
    file: ~/docker-secrets/dbusr
  cert.pem:
    file: ~/docker-secrets/cert.pem
  key.pem: 
    file: ~/docker-secrets/key.pem
  wpsu:
    file: ~/docker-secrets/wpsupw
  wpsu-mail:
    file: ~/docker-secrets/wpsu-mail