name: nginx

services:
  nginx:
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    image: inception-nginx
    ports:
      - "8443:443"
    volumes:
      - wordpress-data:/var/www/html
  wordpress:
    build:
      context: ./srcs/wordpress/
      dockerfile: Dockerfile
    image: inception-wp
    volumes:
      - wordpress-data:/var/www/html
volumes:
  wordpress-data: