name: Inception

services:
  nginx:
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    image: inception-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp-data:/var/www/html
    secrets:
      - cert.pem
      - key.pem

  wp:
    build:
      context: ./srcs/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - db
    image: inception-wp
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp-manager
      WORDPRESS_DB_PASSWORD: /run/secrets/user
    secrets:
      - user

  db:
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    image: inception-mariadb
    secrets:
      - root
      - user
    volumes:
      - mdb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root
      MYSQL_PASSWORD_FILE: /run/secrets/user
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-manager

volumes:
  wp-data:
  mdb-data:

networks:
  inception:
    driver: bridge
    name: inception

secrets:
  root:
    file: ~/docker-secrets/root
  user:
    file: ~/docker-secrets/user
  cert.pem:
    file: ~/docker-secrets/cert.pem
  key.pem: 
    file: ~/docker-secrets/key.pem
  wpsu:
    file ~/docker-secrets/wpsupw